image: Visual Studio 2019
platform:
  - x86
  - x64
configuration: Release

build_script:
  - cmd: cmake -H. -B_build
  - cmd: cmake --build _build --config Release
  - cmd: cd _build
  - cmd: ls
  - cmd: cpack -G NSIS
  - cmd: cd ..

artifacts:
  - path: ./_build/*.exe
    name: solver
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release description'
  provider: GitHub
   auth_token:
    secure: zutZBbjGgZCL8JNohNEDDRGtEXQbPXTqErTejCLF63dkplvpaxyQ+rXjRl22jbKk
  artifact: solver
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true
    APPVEYOR_REPO_TAG: true
