language: cpp
jobs:
  include:
  - os: osx
    script:
    - cmake -H. -B_build
    - cmake --build _build
    - cd _build
    - cpack -G DragNDrop
    - cd ..
  - os: linux
    script:
    - cmake -H. -B_build
    - cmake --build _build
    - cd _build
    - cpack -G DEB
    - cpack -G RPM
    - cd ..
addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - rpm
deploy:
  provider: releases
  api_key:
    secure: 1fHRH1NjNqd2esW0AMu7yC1dG00wAaHfn0Wbo3DFfwXNyxQ7dIpsN/8KgtJLdLYqkypQm8mlnZrjIcPqe2Oe5WMpG8xrKE2c0lPSiaoA9MYvzb9DzBXfrcWHhMT0Z4SRNXWn0et65PG2dj4zzeluI3i6ImokdKdcPO8L8xl8/Ca/LC5zBZkAYg7X8iGnvUhm3a8QT7t13xXbocWNksQe1VWubsmqUEy9slfKb8/2togIdM968QpEbaogQyx0WDw5yc05UfamIPzSbmeF7gd53qekMWaVMR6HB0eqj3PPMvGOAMkD5ZxWyoMlUmWMesKHTl6FjRKXwt1qB6JXhiJpbjrVywzlYjGJTPx/A871d8C0Tu0H+7YnPO1D8OeJ9xLHFZ8z1TvvjYsstoJydA+uXP94XV4gAecJ+QOpIg85sK4MkiKFDnJTdFWC8ghUYf2UX4IL+imbegOslyWdMgGzHV7JgfVkP3Nh9uml/CMQyT1Eauu7U+2zJJqtAgoZPz7eOnyx85ICMdj5ooOrY53lhndYy1SfM5j64oOIHHI0xCSNomGmx8uUuYm6riqS0qRvQMENZxPpdEiJq9ux116yQfTEErdiy6VTigUeIh5XIG3d+FdYLS6wnMG6qtEntDHxMfRWgIzxJUuIIwh911W6WuWVBR5AqfidASNIfJ3MYVA=
  file: 
    - ./_build/solver-1.0.0.-Darwin.dmg
    - ./_build/solver-1.0.0.-Linux.deb
    - ./_build/solver-1.0.0.-Linux.rpm
  skip_cleanup: true
  on:
    repo: AntonGrigorev/hw06
    tags: true
    all_branches: true
env:
  global:
    secure: GRcquFuMyaHcNnRj7KWOm9AbNwxlc1pKjMkE9iuXCpv2Q9WZv3AjmniwySz1Gw69WoumO5q2p2TdSGioTr+oiNP0aZZmfat038rqWgvlBLeqgG7YHiiFC5PBlgg6SVIfgcqomYg3i3iPBpvQGcqQP7FyA94HLs5y12kqnVkGa87xh9Fcvg4keLrt2IwmLKUSsxk5zDW2YB3BJoe/hUcieL+xQdkwO/cuLCf6y+gIp35scBeog4m6lPcFV386+RROWc8hwZy3zX26y1w2JRinHMyxis76zChTe5JpCTaBtGgGn344NqyfcFx1acbQ0+XlyFV5Xo9WZYSSr8OJes4EBxUQ+lLnkqeF90VQcF6XBnt3NdkP4tnNt16uxtoPcsdlMymwgAE4XLJKmWRyhS1PS8rfVT+IkHR/NNgjC/LhuLSQrlZ0LG9N33nQ96itBL83Yq54yoPXsYTK2+Q0oTu8tnzuwOnK4telrEesUnf0SmgRW3CTwYv3Clcvesvq/sa+E8gjBx09JNNmoOlv8elAKPDHGWhm6GynQDFMit6gJcboQKRaP3t1NnPH9IrVaEB015lyNAzI6/Nqj+G1lfHuH1v4alZIDC7pDfTuwwe/OcZwxO40V85mJLW3pTzx2oBb0kEjeA1nwi/x3XNrM4ue9JPv6b3Ko3sgxgrhl1QCpxI=
